server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/android_api
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload:
    path: D:/upload/ # 上传文件地址
    uriPath: /upload/ # 上传文件访问时地址 如：http://localhost:8080/upload/xxx.jpg
